name: CI

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: '17'

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Validate binary compatibility
        run: ./gradlew apiCheck

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          profile: Galaxy Nexus
          script: ./gradlew :grid:connectedDebugAndroidTest --stacktrace
          heap-size: 2048M

  release:
    name: Release
    runs-on: macos-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') && (github.repository == 'cheonjaeung/gridlayout-compose') }}
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: '17'

      - name: Publish to Maven Central
        run: ./gradlew publish --stacktrace
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
